name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build-arch-qt5:
    name: Build ArchLinux Qt5
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: |
          pacman -Syu --noconfirm cmake pkg-config ninja extra-cmake-modules qt5-base qt5-tools kcoreaddons kwidgetsaddons kdoctools kconfigwidgets kcrash kdbusaddons kxmlgui ki18n qt5-charts knotifications gtest xorg-server-xvfb gcovr xdotool pacman-contrib kdesu git
        shell: bash

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRUN_TESTS=ON

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        shell: bash

      - name: Run Tests
        run: |
          export QT_DEBUG_PLUGINS=1
          xvfb-run -s "-screen 0 1920x1080x24 -nolisten local" ${{github.workspace}}/build/bin/pak-qtests
          gcovr -r . -j 2 -f src/src/.*cpp
        shell: bash
