name: pak-gui

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu-qt5:
    runs-on: ubuntu-latest
    steps:
      - name: initialize
        uses: actions/checkout@v2
      - name: update
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -fy
      - name: dependencies
        run: sudo apt install -f -y extra-cmake-modules gettext qt5-default libqt5test5 gcovr libgtest-dev libkf5coreaddons-dev libkf5widgetsaddons-dev kdoctools-dev libkf5doctools-dev libkf5configwidgets-dev libkf5crash-dev libkf5dbusaddons-dev libkf5xmlgui-dev libkf5i18n-dev libqt5charts5-dev libkf5notifications-dev
      - name: build and test
        run: |
          mkdir build
          cd build
          cmake -DRUN_TESTS=ON ..
          make
          make test
          gcovr -r .
